apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - name: http-portee
    port: 80
    protocol: TCP
    targetPort: http-port
  - name: ssh-portee
    port: 22
    protocol: TCP
    targetPort: ssh-port
  selector:
    app: website
  type: NodePort
