apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-slave-deploy
  namespace: jenkins
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-ubuntu-slave
  template:
      metadata:
        labels:
          app: jenkins-ubuntu-slave
      spec:
        serviceAccountName: jenkins-account
        containers:
        - name: jenkins-ubuntu-slave
          image: docker.io/hadilotfy/jenkins-ubuntu-slave:v0 
          imagePullPolicy: Never
          ports:
          - containerPort: 22
            protocol: TCP
            name: slave-ssh-port
          volumeMounts:
          - mountPath: /var/run/docker.sock                  # need chmod
            name: docker-sock
        volumes:        
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                  - jenkins

##  may need to add to user data : ascript to make docker.sock accessible through all nodes.
# 
# need to add to image:
#    1- default password for user jenkins
#    2- start ssh
#    3- chmod 777 /var/jenkins_home
#    4- install aws cli  
#       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#       apt-get update
#       apt-get install unzip
#       unzip awscliv2.zip
#       ./aws/install
#    5- su - jenkins ; aws configure    # after loging-in as jenkins  #  need aws access key ID   and    aws secret access key
#         aws_access_key_id = *****************
#         aws_secret_access_key = *******************************
#    6-create ~/.kube/config
#         aws eks --region us-east-1 update-kubeconfig --name webapp-cluster --profile default
#    