apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: hadilotfy/jenkins-ubuntu-slave:v0
        name: ssh-image
        imagePullPolicy: IfNotPresent
        # ports:
        # - containerPort: 22
        #   name: ssh-port
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - jenkins


