apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins
spec:
  ports:
  # - name: http-porte
  #   port: 80
  #   protocol: TCP
  #   targetPort: http-port
  - name: jenkins-porte
    port: 8080
    protocol: TCP
    targetPort: jenkins-port
    nodePort: 32080
  # - name: ssh-porte
  #   port: 22
  #   protocol: TCP
  #   targetPort: ssh-port
  selector:
    app: jenkins
  type: NodePort
